# Generated by Django 4.1.7 on 2023-03-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialnetwork", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("confirm_password", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.FileField(blank=True, upload_to=""),
        ),
    ]
