# Generated by Django 4.1.5 on 2023-05-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialnetwork", "0004_alter_profile_profile_picture_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.FileField(blank=True, upload_to="socialnetwork/static/images"),
        ),
    ]
